/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package structgps;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gpsdata_t implements lcm.lcm.LCMEncodable
{
    public float time;
    public float lat;
    public float lon;
    public float alt;
    public float utm_x;
    public float utm_y;
 
    public gpsdata_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x153c437e60eed82bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(structgps.gpsdata_t.class))
            return 0L;
 
        classes.add(structgps.gpsdata_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.time); 
 
        outs.writeFloat(this.lat); 
 
        outs.writeFloat(this.lon); 
 
        outs.writeFloat(this.alt); 
 
        outs.writeFloat(this.utm_x); 
 
        outs.writeFloat(this.utm_y); 
 
    }
 
    public gpsdata_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gpsdata_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static structgps.gpsdata_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        structgps.gpsdata_t o = new structgps.gpsdata_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time = ins.readFloat();
 
        this.lat = ins.readFloat();
 
        this.lon = ins.readFloat();
 
        this.alt = ins.readFloat();
 
        this.utm_x = ins.readFloat();
 
        this.utm_y = ins.readFloat();
 
    }
 
    public structgps.gpsdata_t copy()
    {
        structgps.gpsdata_t outobj = new structgps.gpsdata_t();
        outobj.time = this.time;
 
        outobj.lat = this.lat;
 
        outobj.lon = this.lon;
 
        outobj.alt = this.alt;
 
        outobj.utm_x = this.utm_x;
 
        outobj.utm_y = this.utm_y;
 
        return outobj;
    }
 
}

